# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_myuser_fax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='calpro',
        ),
        migrations.AlterField(
            model_name='cashflow_actuals',
            name='actualamount',
            field=models.DecimalField(verbose_name='ACTUAL AMOUNT', decimal_places=2, max_digits=8),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='cashflow_actuals',
            name='acurrency',
            field=models.CharField(max_length=3, verbose_name='CURRENCY', choices=[('USD', 'USD'), ('INR', 'INR')], default='USD'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='cashflow_actuals',
            name='amount',
            field=models.DecimalField(verbose_name='AMOUNT', decimal_places=2, max_digits=8),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='cashflow_actuals',
            name='cashflow_id',
            field=models.CharField(max_length=20),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='cashflow_actuals',
            name='category',
            field=models.ForeignKey(to='user.expense_categories', verbose_name='EXPENSE TYPE'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='cashflow_actuals',
            name='city',
            field=models.CharField(blank=True, max_length=75, verbose_name='CITY', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='cashflow_actuals',
            name='corpid',
            field=models.CharField(max_length=20),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='cashflow_actuals',
            name='currency',
            field=models.CharField(max_length=3, verbose_name='CURRENCY', choices=[('USD', 'USD'), ('INR', 'INR')], default='USD'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='cashflow_actuals',
            name='direction',
            field=models.CharField(max_length=75, verbose_name='DIRECTION', choices=[('I', 'Incoming'), ('O', 'Expense')], default='O'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='cashflow_actuals',
            name='fax',
            field=models.CharField(blank=True, max_length=12, verbose_name='FAX', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='cashflow_actuals',
            name='fdate',
            field=models.DateField(verbose_name='DATE', default=datetime.date(2014, 11, 27)),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='cashflow_actuals',
            name='frequency',
            field=models.CharField(max_length=1, verbose_name='FREQUENCY', choices=[('M', 'Monthly'), ('W', 'Weekly'), ('D', 'Daily'), ('B', 'Bi Weekly'), ('Q', 'Quarterly'), ('H', 'Half Yearly'), ('Y', 'Yearly'), ('S', 'Custom')], default='C'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='cashflow_actuals',
            name='name',
            field=models.CharField(blank=True, max_length=75, verbose_name='NAME', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='cashflow_actuals',
            name='notes1',
            field=models.CharField(blank=True, max_length=75, verbose_name='NOTES1', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='cashflow_actuals',
            name='notes2',
            field=models.CharField(blank=True, max_length=75, verbose_name='NOTES2', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='cashflow_actuals',
            name='notes3',
            field=models.CharField(blank=True, max_length=75, verbose_name='NOTES3', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='cashflow_actuals',
            name='paymethod',
            field=models.CharField(max_length=1, verbose_name='TYPE OF PAYMENT', choices=[('C', 'CARD'), ('W', 'WIRE'), ('B', 'CASH')], default='C'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='cashflow_actuals',
            name='recipient',
            field=models.CharField(blank=True, max_length=75, verbose_name='PAYER/RECIPIENT', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='cashflow_actuals',
            name='region',
            field=models.CharField(blank=True, max_length=2, verbose_name='REGION', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='cashflow_actuals',
            name='street',
            field=models.CharField(blank=True, max_length=75, verbose_name='STREET', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='cashflow_actuals',
            name='telephone',
            field=models.CharField(blank=True, max_length=12, verbose_name='TEL:', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='cashflow_actuals',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, verbose_name='ZIPCODE', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contact',
            name='complaint_categ',
            field=models.CharField(max_length=75, verbose_name='Category', choices=[('N', 'New User Registration'), ('G', 'General Query'), ('U', 'Issue with Login'), ('R', 'Issue with Registration'), ('X', 'Forgot Password'), ('Y', 'Issue with transaction'), ('Y', 'Feedback'), ('S', 'Interested')], default='S'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contact',
            name='complaint_text',
            field=models.CharField(max_length=75, verbose_name='DESCRIPTION'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='Email'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contact',
            name='telephone',
            field=models.CharField(blank=True, max_length=12, verbose_name='TEL:', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='expense_categories',
            name='category',
            field=models.CharField(max_length=3, verbose_name='CATEGORY'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='expense_categories',
            name='description',
            field=models.CharField(max_length=75, verbose_name='DESCRIPTION'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='mycashflow',
            name='amount',
            field=models.DecimalField(verbose_name='AMOUNT', decimal_places=2, max_digits=8),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='mycashflow',
            name='category',
            field=models.ForeignKey(to='user.expense_categories', verbose_name='EXPENSE TYPE'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='mycashflow',
            name='city',
            field=models.CharField(blank=True, max_length=75, verbose_name='CITY', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='mycashflow',
            name='corpid',
            field=models.CharField(max_length=20),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='mycashflow',
            name='currency',
            field=models.CharField(max_length=3, verbose_name='CURRENCY', choices=[('USD', 'USD'), ('INR', 'INR')], default='USD'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='mycashflow',
            name='direction',
            field=models.CharField(max_length=75, verbose_name='DIRECTION', choices=[('I', 'Incoming'), ('O', 'Expense')], default='O'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='mycashflow',
            name='fax',
            field=models.CharField(blank=True, max_length=12, verbose_name='FAX', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='mycashflow',
            name='fdate',
            field=models.DateField(verbose_name='DATE', default=datetime.date(2014, 11, 27)),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='mycashflow',
            name='frequency',
            field=models.CharField(max_length=1, verbose_name='FREQUENCY', choices=[('M', 'Monthly'), ('W', 'Weekly'), ('D', 'Daily'), ('B', 'Bi Weekly'), ('Q', 'Quarterly'), ('H', 'Half Yearly'), ('Y', 'Yearly'), ('S', 'Custom')], default='C'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='mycashflow',
            name='name',
            field=models.CharField(blank=True, max_length=75, verbose_name='NAME', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='mycashflow',
            name='notes1',
            field=models.CharField(blank=True, max_length=75, verbose_name='NOTES1', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='mycashflow',
            name='notes2',
            field=models.CharField(blank=True, max_length=75, verbose_name='NOTES2', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='mycashflow',
            name='notes3',
            field=models.CharField(blank=True, max_length=75, verbose_name='NOTES3', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='mycashflow',
            name='paymethod',
            field=models.CharField(max_length=1, verbose_name='TYPE OF PAYMENT', choices=[('C', 'CARD'), ('W', 'WIRE'), ('B', 'CASH')], default='C'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='mycashflow',
            name='recipient',
            field=models.CharField(blank=True, max_length=75, verbose_name='PAYER/RECIPIENT', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='mycashflow',
            name='region',
            field=models.CharField(blank=True, max_length=2, verbose_name='REGION', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='mycashflow',
            name='street',
            field=models.CharField(blank=True, max_length=75, verbose_name='STREET', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='mycashflow',
            name='telephone',
            field=models.CharField(blank=True, max_length=12, verbose_name='TEL:', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='mycashflow',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, verbose_name='ZIPCODE', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='myuser',
            name='TypeofOrg',
            field=models.CharField(max_length=1, verbose_name='Type of Org', choices=[('1', 'Individual'), ('2', 'Organization')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='myuser',
            name='addr1',
            field=models.CharField(blank=True, max_length=60, verbose_name='ADDRESS LINE1', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='myuser',
            name='addr2',
            field=models.CharField(blank=True, max_length=60, verbose_name='ADDRESS LINE2', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='myuser',
            name='city',
            field=models.CharField(blank=True, max_length=30, verbose_name='CITY', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='myuser',
            name='corpid',
            field=models.CharField(max_length=20, verbose_name='Corp.Id'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='myuser',
            name='country',
            field=models.CharField(blank=True, max_length=2, verbose_name='COUNTRY', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='myuser',
            name='currency',
            field=models.CharField(max_length=4, verbose_name='Currency'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='Email', unique=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='FIRST NAME', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='myuser',
            name='fiscal_year',
            field=models.CharField(blank=True, max_length=1, verbose_name='FISCAL', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='myuser',
            name='landline',
            field=models.CharField(blank=True, max_length=20, verbose_name='LAND PHONE', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='LAST NAME', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='myuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='MIDDLE NAME', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='myuser',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, verbose_name='MOBILE', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='myuser',
            name='name1',
            field=models.CharField(blank=True, max_length=120, verbose_name='NAME', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='myuser',
            name='name2',
            field=models.CharField(blank=True, max_length=120, verbose_name='NAME2', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='myuser',
            name='name3',
            field=models.CharField(blank=True, max_length=120, verbose_name='NAME3', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='myuser',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, verbose_name='PINCODE', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='myuser',
            name='title',
            field=models.CharField(blank=True, max_length=2, verbose_name='TITLE', null=True),
            preserve_default=True,
        ),
    ]
